AppEase/Models/Job.cs
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace AppEase.Models
{
    public class Job
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Company Name required")]
        public string CompanyName { get; set; }
        [Required(ErrorMessage = "Job Title required")]
        public string Title { get; set; }
        [Required(ErrorMessage ="Job Description Requied")]
        public string Description { get; set; }

        public int ProfileId { get; set; }

        public virtual Profile? Profile { get; set; }

    }
}

AppEase/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppEase.Models;
using AppEase.Service;
using Microsoft.AspNetCore.Authorization;

namespace AppEase.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        private readonly AppEaseDbContext _context;

        public JobsController(AppEaseDbContext context)
        {
            _context = context;
        }

        // GET: Jobs
        public async Task<IActionResult> Index()
        {
            var appEaseDbContext = _context.Jobs.Include(j => j.Profile);
            return View(await appEaseDbContext.ToListAsync());
        }

        // GET: Jobs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs
                .Include(j => j.Profile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // GET: Jobs/Create
        public IActionResult Create()
        {
            ViewData["ProfileId"] = new SelectList(_context.Profiles, "Id", "Email");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CompanyName,Title,Description,ProfileId")] Job job)
        {
            if (ModelState.IsValid)
            {
                _context.Add(job);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProfileId"] = new SelectList(_context.Profiles, "Id", "Email", job.ProfileId);
            return View(job);
        }

        // GET: Jobs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            ViewData["ProfileId"] = new SelectList(_context.Profiles, "Id", "Email", job.ProfileId);
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CompanyName,Title,Description,ProfileId")] Job job)
        {
            if (id != job.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobExists(job.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProfileId"] = new SelectList(_context.Profiles, "Id", "Email", job.ProfileId);
            return View(job);
        }
        // POST: Jobs/AddJob
        


        // GET: Jobs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs
                .Include(j => j.Profile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var job = await _context.Jobs.FindAsync(id);
            if (job != null)
            {
                _context.Jobs.Remove(job);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobExists(int id)
        {
            return _context.Jobs.Any(e => e.Id == id);
        }
        private async Task<Profile> getProfile(int id)
        {
            var profile = await _context.Profiles.Include(p => p.Jobs).Include(p => p.Address).FirstOrDefaultAsync(p => p.Id == id);
            return profile;
        }
        private async Task<Job> getJob(int id)
        {
            var job = await _context.Jobs.FirstOrDefaultAsync(p => p.Id == id);
            return job;
        }

        [HttpPost("cover-letter")]
        public IActionResult GetCoverLetterPdf([FromForm] Job job)
        {
            Profile profile = getProfile(job.ProfileId).Result;
            Job job1 = getJob(job.Id).Result;
            var pdfBytes = GeneratePdfService.getCoverLetterPdf(job1, profile);
            Response.Headers.Add("Content-Disposition", "inline; filename=cover-letter.pdf");
            return File(pdfBytes, "application/pdf");
        }


        [HttpPost("cover-letter-download")]
        public  IActionResult GetCoverLetterDownloadPdf([FromForm] Job job)
        {

            Profile profile = getProfile(job.ProfileId).Result;
            Job job1 = getJob(job.Id).Result;
            var pdfBytes = GeneratePdfService.getCoverLetterPdf(job1,profile);
            return File(pdfBytes, "application/pdf", "cover-letter.pdf");
        }
    }
}

AppEase/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppEase.Models;
using AppEase.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using AppEase.Areas.Identity.Data;

namespace AppEase.Controllers
{
    [Authorize]
    public class ProfilesController : Controller
    {
        private readonly AppEaseDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProfilesController(AppEaseDbContext context , UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Profiles
        public async Task<IActionResult> Index()
        {
            var id = _userManager.GetUserId(this.User);
            var profile = await _context.Profiles.Where(p => p.userId == id).ToListAsync();
            return View(profile);
        }

        [HttpGet("cover-letter")]
        public IActionResult GetCoverLetterPdf()
        {
            var pdfBytes = GeneratePdfService.getCoverLetterPdf();
            Response.Headers.Add("Content-Disposition", "inline; filename=cover-letter.pdf");
            return File(pdfBytes, "application/pdf");
        }


        [HttpGet("cover-letter-download")]
        public IActionResult GetCoverLetterDownloadPdf()
        {
            var pdfBytes = GeneratePdfService.getCoverLetterPdf();
            return File(pdfBytes, "application/pdf", "cover-letter.pdf");
        }

        // GET: Profiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles.Include(p => p.Jobs).FirstOrDefaultAsync(p => p.Id == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);

        }

        // GET: Profiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Profiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Email,LinkedIn,Github,Resume,SkillSet,Address,userId")] Profile profile)
        {
            var UserId = _userManager.GetUserId(this.User);

            if (ModelState.IsValid && UserId !=null)
            {
                profile.userId = UserId;
                _context.Add(profile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        [HttpPost]
        public async Task<IActionResult> AddJob(int id, [Bind("CompanyName","Title", "Description", "ProfileId")] Job newJob)
        {
            if (ModelState.IsValid)
            {
                var profile = await _context.Profiles.Include(p => p.Jobs).FirstOrDefaultAsync(p => p.Id == id);
                if (profile != null)
                {
                    profile.Jobs ??= new List<Job>();
                    newJob.ProfileId = profile.Id;
                    newJob.Profile = profile;
                    profile.Jobs.Add(newJob);
                    _context.Add(newJob);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Details", new { id });
            }
            return View("Details", id);
        }

        // GET: Profiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles.Include(p => p.Address).FirstOrDefaultAsync( m=> m.Id == id);
            if (profile == null)
            {
                return NotFound();
            }
            return View(profile);
        }

        // POST: Profiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,LinkedIn,Github,Resume,SkillSet,Address,userId")] Profile profile)
        {
            if (id != profile.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(profile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfileExists(profile.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        // GET: Profiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // POST: Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var profile = await _context.Profiles.FindAsync(id);
            if (profile != null)
            {
                _context.Profiles.Remove(profile);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfileExists(int id)
        {
            return _context.Profiles.Any(e => e.Id == id);
        }
    }
}

AppEase/Views/Jobs/Create.cshtml
@model AppEase.Models.Job

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Job</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfileId" class="control-label"></label>
                <select asp-for="ProfileId" class ="form-control" asp-items="ViewBag.ProfileId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppEase/Views/Jobs/Delete.cshtml
@model AppEase.Models.Job

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Profile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Profile.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppEase/Views/Jobs/Details.cshtml
@model AppEase.Models.Job

@{
    ViewData["Title"] = "Details";
}

<h1>Job Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">

            @{
                var resumeWords = Model.Description.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
                var firstTenWords = string.Join(" ", resumeWords.Take(10));
            }
            <span class="short-resume">@firstTenWords</span>
            <span class="full-resume" style="display:none;">@Model.Description View Less</span>

            <a href="javascript:void(0);" class="show-full-resume" onclick="toggleResume(this)">
                <img src="~/images/viewmore.png" alt="Show Full Resume" style="width:25px;height:25px;" />
            </a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Profile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Profile.Email)
        </dd>
    </dl>
</div>


<div>
    <form id="downloadForm" method="post" action="/cover-letter-download" target="_blank">
        <input type="hidden" name="Id" value="@Model.Id" />
        <input type="hidden" name="Title" value="@Model.Title" />
        <input type="hidden" name="CompanyName" value="@Model.CompanyName" />
        <input type="hidden" name="Description" value="@Model.Description" />
        <input type="hidden" name="ProfileId" value="@Model.ProfileId" />
        <button type="submit" class="animated-button">Download Cover Letter PDF</button>
    </form>
</div>

<div>
    <form id="downloadForm" method="post" action="/cover-letter" target="_blank">
        <input type="hidden" name="Id" value="@Model.Id" />
        <input type="hidden" name="Title" value="@Model.Title" />
        <input type="hidden" name="CompanyName" value="@Model.CompanyName" />
        <input type="hidden" name="Description" value="@Model.Description" />
        <input type="hidden" name="ProfileId" value="@Model.ProfileId" />
        <button type="submit" class="animated-button">View Cover Letter PDF</button>
    </form>
    <br />
</div>
@* <div>
    <button onclick="openDownloadPdf()">Download Cover Letter PDF</button>

    <script>
        function openDownloadPdf() {
            window.open('/cover-letter-download', '_blank');
        }
    </script>
</div> *@

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a> |
    <a asp-controller="Profiles" asp-action="Details" asp-route-id="@Model?.ProfileId" class="btn btn-outline-dark">Back to profile</a>
</div>

@section Scripts {
    <script>
        function toggleResume(element) {
            var shortResume = element.previousElementSibling.previousElementSibling;
            var fullResume = element.previousElementSibling;
            if (fullResume.style.display === "none") {
                fullResume.style.display = "inline";
                shortResume.style.display = "none";
            } else {
                fullResume.style.display = "none";
                shortResume.style.display = "inline";
            }
        }
    </script>
}

AppEase/Views/Jobs/Edit.cshtml
@model AppEase.Models.Job

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Job</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfileId" class="control-label"></label>
                <select asp-for="ProfileId" class="form-control" asp-items="ViewBag.ProfileId"></select>
                <span asp-validation-for="ProfileId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppEase/Views/Jobs/Index.cshtml
@model IEnumerable<AppEase.Models.Job>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="addjobanimatedbutton"><span>Create New</span></a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Profile)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Profile.Email)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>